workspace(name = "example")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# CONFIGURE `@dwtj_rules_hugo` ###############################################

DWTJ_RULES_HUGO_SHA256 = "18e0501698993530e23bc7988a6efb7fd8d890c5e1245323dd09f0022805bf9f"
DWTJ_RULES_HUGO_COMMIT = "93e348faebdf3ef8a051789174cead5f99a28ce8"

http_archive(
    name = "dwtj_rules_hugo",
    url = "https://github.com/dwtj/dwtj_rules_hugo/archive/{}.zip".format(DWTJ_RULES_HUGO_COMMIT),
    strip_prefix = "dwtj_rules_hugo-{}".format(DWTJ_RULES_HUGO_COMMIT),
    sha256 = DWTJ_RULES_HUGO_SHA256,
)

load("@dwtj_rules_hugo//hugo:repositories.bzl", "local_hugo_repository")

local_hugo_repository(name = "local_hugo")

load("@local_hugo//:defs.bzl", "register_hugo_toolchain")

register_hugo_toolchain()
