workspace(name = "example")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# NOTE(dwtj): These versions of `@dwtj_rules_hugo` and `@rules_pkg` were chosen
# only because they are the latest releases as of 2020-09-01.

# CONFIGURE `@dwtj_rules_hugo` ###############################################

DWTJ_RULES_HUGO_SHA256 = "0b0b292ea89fc0c29e24a52eb164aa45341c0c46a616e66c0aa87536a4054379"
DWTJ_RULES_HUGO_COMMIT = "9780c52b97addaa53f74a935bab6500099f816bd"

http_archive(
    name = "dwtj_rules_hugo",
    url = "https://github.com/dwtj/dwtj_rules_hugo/archive/{}.zip".format(DWTJ_RULES_HUGO_COMMIT),
    strip_prefix = "dwtj_rules_hugo-{}".format(DWTJ_RULES_HUGO_COMMIT),
    sha256 = DWTJ_RULES_HUGO_SHA256,
)

load("@dwtj_rules_hugo//hugo:repositories.bzl", "local_hugo_repository")

local_hugo_repository(name = "local_hugo")

load("@local_hugo//:defs.bzl", "register_hugo_toolchain")

register_hugo_toolchain()

# CONFIGURE `@rules_pkg` #######################################################

_RULES_PKG_TAG = "0.2.5"
_RULES_PKG_SHA256 = "352c090cc3d3f9a6b4e676cf42a6047c16824959b438895a76c2989c6d7c246a"

http_archive(
    name = "rules_pkg",
    url = "https://github.com/bazelbuild/rules_pkg/releases/download/{0}/rules_pkg-{0}.tar.gz".format(_RULES_PKG_TAG),
    sha256 = _RULES_PKG_SHA256,
)

load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")

rules_pkg_dependencies()
