workspace(name = "example")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# CONFIGURE `@dwtj_rules_hugo` ###############################################

DWTJ_RULES_HUGO_SHA256 = "f0e29fd0ae7913b4770a194f3b5be6d4560be4a5c8a9241e065ef97c1952d9bc"
DWTJ_RULES_HUGO_COMMIT = "25fd6a279e80c58c0c25d33196e6558cbe7ac628"

http_archive(
    name = "dwtj_rules_hugo",
    url = "https://github.com/dwtj/dwtj_rules_hugo/archive/{}.zip".format(DWTJ_RULES_HUGO_COMMIT),
    strip_prefix = "dwtj_rules_hugo-{}".format(DWTJ_RULES_HUGO_COMMIT),
    sha256 = DWTJ_RULES_HUGO_SHA256,
)

load("@dwtj_rules_hugo//hugo:repositories.bzl", "local_hugo_repository")

local_hugo_repository(name = "local_hugo")

load("@local_hugo//:defs.bzl", "register_hugo_toolchain")

register_hugo_toolchain()
