workspace(name = "smoke_test_deps_in_external_repository")

# CONFIGURE `@dwtj_rules_hugo` ################################################

local_repository(
    name = "dwtj_rules_hugo",
    path = "../../..",
)

load("@dwtj_rules_hugo//hugo:repositories.bzl", "local_hugo_repository")

local_hugo_repository(name = "local_hugo")

load("@local_hugo//:defs.bzl", "register_hugo_toolchain")

register_hugo_toolchain()

# CONFIGURE `@my_external_repository` #########################################

local_repository(
    name = "my_external_repository",
    path = "../smoke_test_basic_rules",
)
