workspace(name = "smoke_test_basic_rules")

local_repository(
    name = "dwtj_rules_hugo",
    path = "../../..",
)

# CONFIGURE `@dwtj_rules_hugo` ################################################

load("@dwtj_rules_hugo//hugo:repositories.bzl", "local_hugo_repository")

local_hugo_repository(name = "local_hugo")

load("@local_hugo//:defs.bzl", "register_hugo_toolchain")

register_hugo_toolchain()
