workspace(name = "website")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# CONFIGURE `@dwtj_rules_hugo` REPOSITORY ######################################

local_repository(
    name = "dwtj_rules_hugo",
    path = "..",
)

# CONFIGURE `@local_hugo` REPOSITORY & TOOLCHAIN ###############################

load("@dwtj_rules_hugo//hugo:repositories.bzl", "local_hugo_repository")

local_hugo_repository(name = "local_hugo")

load("@local_hugo//:defs.bzl", "register_hugo_toolchain")

register_hugo_toolchain()

# CONFIGURE `@io_bazel_stardoc` ################################################

_STARDOC_TAG = "0.4.0"
_STARDOC_SHA256 = "6d07d18c15abb0f6d393adbd6075cd661a2219faab56a9517741f0fc755f6f3c"

http_archive(
    name = "io_bazel_stardoc",
    url = "https://github.com/bazelbuild/stardoc/archive/{}.tar.gz".format(_STARDOC_TAG),
    sha256 = _STARDOC_SHA256,
    strip_prefix = "stardoc-{}".format(_STARDOC_TAG),
)

load("@io_bazel_stardoc//:setup.bzl", "stardoc_repositories")

stardoc_repositories()

# CONFIGURE `@rules_pkg` #######################################################

# NOTE(dwtj): This version of `@rules_pkg` was chosen because it is the latest
#  release as of 2020-08-31.
_RULES_PKG_TAG = "0.2.5"
_RULES_PKG_SHA256 = "352c090cc3d3f9a6b4e676cf42a6047c16824959b438895a76c2989c6d7c246a"

http_archive(
    name = "rules_pkg",
    url = "https://github.com/bazelbuild/rules_pkg/releases/download/{0}/rules_pkg-{0}.tar.gz".format(_RULES_PKG_TAG),
    sha256 = _RULES_PKG_SHA256,
)
load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")
rules_pkg_dependencies()
